version: "3"
services:
  web:
    build: .
    command: ["bash", "-c", "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -b '0.0.0.0'"]
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    stdin_open:
      true
    tty:
      true
    
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - '.:/project'
      - '/project/tmp' # don't mount tmp directory
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
  db:
    image: postgres:12.17
    environment:
      POSTGRES_USER: hp
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: my_database_development
    volumes:
      - .:/app
  redis:
    image: redis:5.0.7
    volumes:
      - .:/app
    