---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/categories":
    post:
      summary: Creates a category
      tags:
      - Categories
      parameters: []
      responses:
        '200':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                category_name:
                  type: string
              required:
              - category_name
    get:
      summary: Retrieves all category
      tags:
      - Categories
      responses:
        '200':
          description: categories found
  "/api/categories/{id}":
    get:
      summary: Retrieves a category
      tags:
      - Categories
      parameters:
      - name: id
        in: path
        type: string
        schema:
          type: object
          properties:
            id:
              type: integer
            category_name:
              type: string
          required:
          - id
          - category_name
        required: true
      responses:
        '200':
          description: category not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
