development:
  adapter: postgresql
  encoding: unicode
  database: my_database_development
  pool: 5
  username: hp
  password: PASSWORD
  host: db # This should work within the Docker network

test:
  adapter: postgresql
  encoding: unicode
  database: my_database_test
  pool: 5
  username: hp
  password: PASSWORD
  host: db # This should work within the Docker network

production:
  adapter: postgresql
  encoding: unicode
  database: my_database_production
  pool: 5
  username: hp
  password: PASSWORD
  host: db # This should work within the Docker network
